version: '2'
services:
  # Aldea
  aldea-database:
    image: mariadb:10.1
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: aldea_production
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER:
      MYSQL_PASSWORD:
    volumes:
      - aldea:/var/lib/mysql
    labels:
      io.rancher.container.hostname_override: container_name

  aldea-application:
    image: registry.neec.xyz/neeco/aldea-application:latest
    environment:
      RAILS_LOG_TO_STDOUT: 'true'
      ALDEA_PORT: 3000
      ALDEA_DATABASE_HOST: aldea-database
      ALDEA_DATABASE_USER: $MYSQL_DATABASE
      ALDEA_DATABASE_PASSWORD: $MYSQL_PASSWORD
      ALDEA_SECRET_KEY_BASE:
      # CUENTA_URL: http://cuenta-application:4000/
      # IMAGEN_URL: http://imagen-application:8000/
      # STATIC_IMAGE_URL:
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: aldea-database